name: Sync

on:
  schedule:
    - cron: '57 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: cd $GITHUB_WORKSPACE
      - run: cp -f git-config ./.git/config
      - run: git pull --all
      - run: git push --all

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install git-parse
      - run: |
          node -e "require('git-parse').gitToJs('.').then(c=>console.log(JSON.stringify(c)));" > commits.json
          head commits.json
