name: Sync

on:
  schedule:
    - cron: '57 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: sirdarckcat/linux-mirror
          path: ./linux-mirror

      - uses: actions/checkout@v2
        with:
          repository: sirdarckcat/linux-1
          fetch-depth: 0
          path: ./linux-1

      - name: Update mirror
        working-directory: ./linux-1
        run: |
          git remote rename origin github
          git remote add upstream https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux
          git remote add -t master torvalds https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux
          git config branch.master.remote torvalds
          git config branch.master.merge refs/heads/master
          git config remote.upstream.pushurl $(git config remote.github.url)
          git config remote.torvalds.pushurl $(git config remote.github.url)
          git pull upstream --all
          git pull torvalds --all
          git push github --all
