name: Sync

on:
  schedule:
    - cron: '57 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: linux

      - uses: actions/checkout@v2
        with:
          repository: sirdarckcat/linux-mirror
          path: mirror

      - run: cd $GITHUB_WORKSPACE/linux
      - run: git remote rename origin github
      - run: git remote add upstream https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux
      - run: git remote add -t master torvalds https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux
      - run: git config branch.master.remote torvalds
      - run: git config branch.master.merge refs/heads/master
      - run: git config remote.upstream.pushurl $(git config remote.github.url)
      - run: git config remote.torvalds.pushurl $(git config remote.github.url)
      - run: git pull --all
      - run: git push --all
      - run: cd $GITHUB_WORKSPACE/linux
      - run: git log --all --format=format:'%H%x09%(trailers:key=Fixes,separator=%x09,valueonly=true)' > ../mirror/fixes.tsv
      - run: git log --all --format=format:'%H%x09%(trailers:key=Reported-by,separator=%x09,valueonly=true)' | grep syzkaller > ../mirror/reported_by.tsv
      - run: git name-rev --tags --all | sed s/\ /$'\t'/g > ../mirror/tags.tsv
      - run: git log --all --all-match -E --grep='\b[0-9a-f]{40}\b' --grep=pstream | grep '[0-9a-f]\{40\}' | grep '^commit \|Upstream commit\|commit.*upstream' | sed 's/\(\s*\).*\([0-9a-f]\{40\}\).*/\1\2/' | sed ':a;N;$!ba;s/\n \+/\t/g' > ../mirror/upstream.tsv
      - run: |
          cd ../mirror
          git add fixes.tsv reported_by.tsv tags.tsv upstream.tsv
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m '[automatic] update tsvs'
          git push
