name: Sync

on:
  schedule:
    - cron: '57 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: cd $GITHUB_WORKSPACE
      - run: cat .git/config
      - run: git remote rename origin github
      - run: git remote add upstream https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux
      - run: git remote add -t master torvalds https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux
      - run: git config branch.master.remote torvalds
      - run: git config branch.master.merge refs/heads/master
      - run: git config remote.upstream.pushurl $(git config remote.github.url)
      - run: git config remote.torvalds.pushurl $(git config remote.github.url)
      - run: cat .git/config
      - run: git pull --all
      - run: git push --all

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install git-parse
      - run: |
          node -e "require('git-parse').gitToJs('.').then(c=>console.log(JSON.stringify(c)));" > commits.json
          head commits.json
