name: Sync

on:
  schedule:
    - cron: '57 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          cd $GITHUB_WORKSPACE
          cp -f git-config ./.git/config
          git pull --all
          git push --all
