name: Sync

on:
  schedule:
    - cron: '57/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update mirror
        run: |
          git remote rename origin github
          git remote add upstream https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux
          git remote add -t master torvalds https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux
          git config branch.master.remote torvalds
          git config branch.master.merge refs/heads/master
          git config remote.upstream.pushurl $(git config remote.github.url)
          git config remote.torvalds.pushurl $(git config remote.github.url)
          git pull --all
          git push -f github 'refs/remotes/upstream/*:refs/heads/*'
          git push github 'refs/remotes/torvalds/master:refs/heads/master'
          git push github --tags
