name: Syzkaller

on:
  workflow_dispatch:
  schedule:
    - cron: '20 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      id-token: 'write'

    env:
      BUCKET_NAME: linux-mirror-db

    steps:
      - name: Dump Syzkaller commit IDs
        run: |
          echo syzkaller,commit > syzkaller.csv
          curl https://syzkaller.appspot.com/upstream/fixed?json=1 | jq -r '.Bugs[] | (.link as $link | [$link, .["fix-commits"][]?.hash]) | @csv' | sed s#/bug.##g >> syzkaller.csv
          head syzkaller.csv

      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/799795028847/locations/global/workloadIdentityPools/github-pool/providers/github-provider-new'
          service_account: 'github@sdcpocs.iam.gserviceaccount.com'

      - uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          destination: '${{ env.BUCKET_NAME }}/'
          path: ./
          glob: 'syzkaller.*'
          headers: |-
            cache-control: no-cache
