name: Syzkaller

on:
  workflow_dispatch:
  schedule:
    - cron: '20 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'
      id-token: 'write'

    env:
      BUCKET_NAME: linux-mirror-db

    steps:
      - name: Dump Syzkaller commit IDs
        run: |
          wget https://linux-mirror-db.storage.googleapis.com/reported_by.csv
          cat reported_by.csv | jq -r --raw-input 'split("\n")|map("["+.+"]"|fromjson)[]|[.[0],(.[1] | scan("syzbot\\+([0-9a-f]+)@") | "extid=" + .[])] | @csv' | uniq > syzkaller_extid.txt
          curl https://syzkaller.appspot.com/upstream/fixed?json=1 | jq -r '.Bugs[] | (.link as $link | .["fix-commits"][]?.hash | select( . != null ) | [., $link[5:]]) | @csv' > syzkaller_fixed.txt
          echo commit,syzkaller > syzkaller.csv
          cat syzkaller_*.txt | sort | uniq | grep , | grep -v : >> syzkaller.csv
          wc -l syzkaller.csv
          head syzkaller.csv

      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/799795028847/locations/global/workloadIdentityPools/github-pool/providers/github-provider-new'
          service_account: 'github@sdcpocs.iam.gserviceaccount.com'

      - uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          destination: '${{ env.BUCKET_NAME }}/'
          path: ./
          glob: 'syzkaller.*'
          headers: |-
            cache-control: no-cache
